# frozen_string_literal: true

module LicenseConflicts
  CONFLICTS_MAP = {
    'MIT' => [
      'zlib/libpng license',
      'Mozilla Public License 1.1',
      'Common Development and Distribution License 1.0',
      'AGPL-1.0+',
      'MPL-1.1+'
    ],
    'Simplified BSD' => [
      'MIT',
      'zlib/libpng license',
      'Mozilla Public License 1.1',
      'Common Development and Distribution License 1.0',
      'AGPL-1.0+'
    ],
    'New BSD' => [
      'MIT',
      'Simplified BSD',
      'zlib/libpng license',
      'Mozilla Public License 1.1',
      'Common Development and Distribution License 1.0',
      'AGPL-1.0+'
    ],
    'Apache 2.0' => [
      'MIT',
      'New BSD',
      'Simplified BSD',
      'zlib/libpng license',
      'Mozilla Public License 1.1',
      'Common Development and Distribution License 1.0',
      'AGPL-1.0+'
    ],
    'zlib/libpng license' => [
      'MIT',
      'New BSD',
      'Simplified BSD',
      'Mozilla Public License 1.1',
      'Common Development and Distribution License 1.0',
      'AGPL-1.0+'
    ],
    'AFL-3.0' => [
      'MIT',
      'Simplified BSD',
      'New BSD',
      'Apache 2.0',
      'Mozilla Public License 1.1',
      'Mozilla Public License 2.0',
      'MPL-1.1+',
      'Common Development and Distribution License 1.0',
      'GNU Lesser General Public License version 2.1',
      'LGPL',
      'GPLv2',
      'GPLv3',
      'AGPL-3.0',
      'zlib/libpng license',
      'AGPL-1.0+'
    ],
    'Mozilla Public License 1.1' => [
      'MIT',
      'Simplified BSD',
      'New BSD',
      'Apache 2.0',
      'zlib/libpng license',
      'AFL-3.0',
      'MPL-1.1+',
      'LGPL',
      'OSL-3.0',
      'AGPL-1.0+'
    ],
    'Mozilla Public License 2.0' => [
      'MIT',
      'Simplified BSD',
      'New BSD',
      'Apache 2.0',
      'zlib/libpng license',
      'AFL-3.0',
      'Mozilla Public License 1.1',
      'MPL-1.1+',
      'Common Development and Distribution License 1.0',
      'LGPL',
      'OSL-3.0',
      'AGPL-1.0+'
    ],
    'MPL-1.1+' => [
      'MIT',
      'Simplified BSD',
      'New BSD',
      'Apache 2.0',
      'zlib/libpng license',
      'AFL-3.0',
      'Mozilla Public License 1.1',
      'Mozilla Public License 2.0',
      'Common Development and Distribution License 1.0',
      'GNU Lesser General Public License version 2.1',
      'LGPL',
      'OSL-3.0',
      'GPLv2',
      'GPLv3',
      'AGPL-3.0',
      'AGPL-1.0+'
    ],
    'Common Development and Distribution License 1.0' => [
      'MIT',
      'Simplified BSD',
      'New BSD',
      'Apache 2.0',
      'zlib/libpng license',
      'AFL-3.0',
      'Mozilla Public License 1.1',
      'Mozilla Public License 2.0',
      'MPL-1.1+',
      'GNU Lesser General Public License version 2.1',
      'LGPL',
      'OSL-3.0',
      'GPLv2',
      'GPLv3',
      'AGPL-3.0',
      'AGPL-1.0+'
    ],
    'GNU Lesser General Public License version 2.1' => [
      'MIT',
      'Simplified BSD',
      'New BSD',
      'Apache 2.0',
      'zlib/libpng license',
      'AFL-3.0',
      'Mozilla Public License 1.1',
      'Mozilla Public License 2.0',
      'MPL-1.1+',
      'Common Development and Distribution License 1.0',
      'OSL-3.0',
      'AGPL-1.0+'
    ],
    'OSL-3.0' => [
      'MIT',
      'Simplified BSD',
      'New BSD',
      'Apache 2.0',
      'zlib/libpng license',
      'AFL-3.0',
      'Mozilla Public License 1.1',
      'Mozilla Public License 2.0',
      'MPL-1.1+',
      'Common Development and Distribution License 1.0',
      'GNU Lesser General Public License version 2.1',
      'LGPL',
      'GPLv2',
      'GPLv3',
      'AGPL-3.0',
      'AGPL-1.0+'
    ],
    'GPLv2' => [
      'MIT',
      'Simplified BSD',
      'New BSD',
      'Apache 2.0',
      'zlib/libpng license',
      'AFL-3.0',
      'Mozilla Public License 1.1',
      'Mozilla Public License 2.0',
      'MPL-1.1+',
      'Common Development and Distribution License 1.0',
      'GNU Lesser General Public License version 2.1',
      'LGPL',
      'OSL-3.0',
      'AGPL-1.0+'
    ],
    'GPLv3' => [
      'MIT',
      'Simplified BSD',
      'New BSD',
      'Apache 2.0',
      'zlib/libpng license',
      'AFL-3.0',
      'Mozilla Public License 1.1',
      'Mozilla Public License 2.0',
      'MPL-1.1+',
      'Common Development and Distribution License 1.0',
      'GNU Lesser General Public License version 2.1',
      'LGPL',
      'OSL-3.0',
      'GPLv2',
      'AGPL-1.0+'
    ],
    'AGPL-3.0' => [
      'MIT',
      'Simplified BSD',
      'New BSD',
      'Apache 2.0',
      'zlib/libpng license',
      'AFL-3.0',
      'Mozilla Public License 1.1',
      'Mozilla Public License 2.0',
      'MPL-1.1+',
      'Common Development and Distribution License 1.0',
      'GNU Lesser General Public License version 2.1',
      'LGPL',
      'OSL-3.0',
      'GPLv2',
      'GPLv3',
      'AGPL-1.0+'
    ],
    'AGPL-1.0+' => [
      'MIT',
      'Simplified BSD',
      'New BSD',
      'Apache 2.0',
      'zlib/libpng license',
      'AFL-3.0',
      'Mozilla Public License 1.1',
      'Mozilla Public License 2.0',
      'MPL-1.1+',
      'Common Development and Distribution License 1.0',
      'GNU Lesser General Public License version 2.1',
      'LGPL',
      'OSL-3.0',
      'GPLv2',
      'GPLv3'
    ]
  }.freeze
end